language: rust
script:
  - cargo build --verbose
notifications:
  email:
    on_success: never
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
